TileDB-Inc/TileDB-MariaDB

- mytile/ha_mytile.cc
Update plugin author and description
> Update plugin author and description

- README.md
- docker/Dockerfile
- docker/Dockerfile-dev
- docker/Dockerfile-server
Update dockerfile and instructions
> Update dockerfile and instructions

- mysql-test/mytile/r/discovery.result
- mysql-test/mytile/t/discovery.test
- mytile/ha_mytile.cc
> Only read unordered only for sparse arrays

- README.md
- mytile/ha_mytile.cc
- mytile/ha_mytile.h
- mytile/mytile-discovery.cc
- mytile/mytile-discovery.h
- mytile/mytile-range.cc
- mytile/mytile-range.h
- mytile/mytile.h
> General cleanup

- azure-pipelines.yml
- mytile/ha_mytile.cc
- scripts/azure-linux_mac.yml
Also only call query submit if there is data to write.
Finalize is only effective if the array is being written to in global order. Currently unordered is the layout for all writes in MyTile.
> Only call finalize if in global order

- docker/Dockerfile
- docker/Dockerfile-dev
- docker/Dockerfile-server
- scripts/ci_install_tiledb_and_run_tests.sh
> Update to TileDB 1.7

- mytile/ha_mytile.cc
- mytile/utils.h
Add support for setting context tags from config
> Add support for setting context tags from config

- mytile/ha_mytile.cc
Trim whitespace from user configs
> Trim whitespace from user configs

- mysql-test/mytile/r/pushdown_ranges.result
- mysql-test/mytile/t/pushdown_ranges.test
- mytile/ha_mytile.cc
- mytile/ha_mytile.h
- mytile/mytile-range.cc
- mytile/mytile-range.h
This combines ranges into super ranges. We also fix using epsilon for real domains. Additional unit tests were add.
Support for OR is still not supported, this will be a follow up PR.
> Correctly handle range conditions for pushdown

- mytile/ha_mytile.cc
- mytile/ha_mytile.h
- mytile/mytile-range.h
Remove all use of table locks, none are needed
> Remove all use of table locks, none are needed

- mytile/mytile-discovery.cc
This removes a lot of verbose output from the logs when we fail to load an array schema on a non-exist array
> Use VFS and Object for array discovery

- mytile/mytile.cc
Use TILEDB_ASCII_STRING for varchar fields
> Use TILEDB_ASCII_STRING for varchar fields

- mysql-test/mytile/r/data_types.result
- mysql-test/mytile/r/primary_key.result
- mysql-test/mytile/r/pushdown_ranges.result
- mysql-test/mytile/t/data_types.test
- mysql-test/mytile/t/primary_key.test
- mysql-test/mytile/t/pushdown_ranges.test
- mytile/ha_mytile.cc
- mytile/ha_mytile.h
- mytile/mytile-range.cc
- mytile/mytile-range.h
- mytile/mytile.cc
- mytile/mytile.h
Add support for string dimensions. This includes updated primary key support.
MRR support is left for a future PR.
> Add support for string dimensions

- docker/Dockerfile
- docker/Dockerfile-dev
- docker/Dockerfile-server
- scripts/ci_install_tiledb_and_run_tests.sh
Enable GCS and update to TileDB 2.0.3
> Enable GCS and update to TileDB 2.0.3

- CMakeLists.txt
- docker/Dockerfile
- docker/Dockerfile-dev
- docker/Dockerfile-server
- scripts/ci_install_tiledb_and_run_tests.sh
> Update to TileDB 2.0.7

- CMakeLists.txt
- docker/Dockerfile
- docker/Dockerfile-dev
- docker/Dockerfile-server
- scripts/ci_install_tiledb_and_run_tests.sh
> Update to TileDB 2.0.8

- mytile/ha_mytile.cc
Update plugin maturity to beta
> Update plugin maturity to beta

- mysql-test/mytile/r/datetimes.result
- mysql-test/mytile/t/datetimes.test
Added testing for each datetime / timestamp type.
> add mysql tests for timestamp / datetime / date / year

- mytile/ha_mytile.cc
Return HA_ERR_END_OF_FILE when query is empty
> Return HA_ERR_END_OF_FILE when query is empty

- scripts/azure-linux_mac.yml
Workaround taken from github actions issue:
https://github.com/actions/virtual-environments/issues/1811
> Workaround homebrew openssl error for CI

- mytile/mytile-discovery.cc
- mytile/mytile.cc
Handle escaping null delimiter defaults
> Handle escaping null delimiter defaults

- scripts/ci_install_tiledb_and_run_tests.sh
Add downloading prebuilt libs for linux/macos for CI
> Add downloading prebuilt libs for linux/macos for CI

- CMakeLists.txt
- docker/Dockerfile
- docker/Dockerfile-dev
- docker/Dockerfile-min
- docker/Dockerfile-server
- scripts/ci_install_tiledb_and_run_tests.sh
> Update to TileDB 2.2.3

- mytile/ha_mytile.cc
The multi-range reads to handle zero length strings like we do for normal pushdown.
> MRR needs to handle zero length strings

- mytile/ha_mytile.cc
index_next_same should conditional reset indexes
> index_next_same should conditional reset indexes

- docker/Dockerfile-R
This started as a modification to the main Dockerfile (hence the branch name) but morphed into a new added Dockerfile to create an R-based container with TileDB and MyTile functionality via RMariaDB.
> Add R-based container to demonstrate RMariaDB functionality

- azure-pipelines.yml
Update azure pipelines to build new R image. Also fix incorrect mariadb-server image building.
> Update azure pipelines to build new R image

- CMakeLists.txt
- docker/Dockerfile
- docker/Dockerfile-R
- docker/Dockerfile-dev
- docker/Dockerfile-min
- docker/Dockerfile-server
- scripts/ci_install_tiledb_and_run_tests.sh
> Update for TileDB 2.2.7

- CMakeLists.txt
- docker/Dockerfile
- docker/Dockerfile-R
- docker/Dockerfile-dev
- docker/Dockerfile-min
- docker/Dockerfile-server
- scripts/ci_install_tiledb_and_run_tests.sh
> Update to TileDB 2.2.8

- CMakeLists.txt
- scripts/azure-linux_mac.yml
- scripts/ci_install_tiledb_and_run_tests.sh
> Update TileDB to 2.2.9

- mytile/ha_mytile.cc
Update version numbers for 0.9.6
> Update version numbers for 0.9.6

- mytile/ha_mytile.cc
Update internal engine version to 0.10.0
> Update internal engine version to 0.10.0

- docker/Dockerfile-min
Fix shortsha for min dockerfile
> Fix shortsha for min dockerfile

- azure-pipelines.yml
Update docker build to ubuntu-22.04
> Update docker build to ubuntu-22.04

- mysql-test/mytile/r/spatial_index.result
- mytile/ha_mytile.cc
This is a side-effect of the previous update to MyTile 10.5.21. This PR fixes the issue
> fix a bug that prevented the spatial pushdown

- .github/workflows/docker.yaml
Fix dockerhub repository names
> Fix dockerhub repository names

- scripts/ci/build-tiledb-mariadb.sh
Problem fixed! Thanks for the suggestion @Shelnutt2.
> add ```-Wno-error=switch``` in nightly

- mysql-test/mytile/r/filters.result
- mysql-test/mytile/r/multi_value_fixed_length.result
- mysql-test/mytile/r/nullable_attributes.result
- mysql-test/mytile/t/filters.test
- mytile/ha_mytile.cc
- mytile/mytile-discovery.cc
- mytile/mytile.h
> add support for validity filters

- scripts/ci/setup-macos.sh
> fix issue 322

- .github/workflows/nightly.yaml
- scripts/ci/setup-macos.sh
Closes #324 (hopefully 🤞)
cc: @DimitrisStaratzis, @teo-tsirpanis
> Install automake on MacOS to build libmagic

- mytile/ha_mytile.cc
- mytile/ha_mytile.h
- mytile/mytile-discovery.cc
- mytile/mytile-range.cc
- mytile/mytile-range.h
- mytile/mytile-statusvars.cc
- mytile/mytile-sysvars.cc
- mytile/mytile.cc
- mytile/utils.cc
clang format has not been applied for a long time in this repo and it is not checked by the CI.
> clang format

- mytile/ha_mytile.cc
This PR will move mytile away from using deprecated methods.
[sc-46049]
> move away from deprecated TileDB methods

- mysql-test/mytile/r/enum.result
- mysql-test/mytile/t/enum.test
- mytile/ha_mytile.cc
[sc-47155]
Small adjustment. Pointed by @Shelnutt2
> small adjustment to enum tests

- mytile/mytile-discovery.cc
This PR fixes the nightly failures seen in #358. It chnages the code to use the new constructors for the ```Array``` and ```ArraySchema``` classes. It also maintains the use of the old constructors to keep backwards compatibility when using this storage engine with an older version of TileDB
Nightly run  here: https://github.com/TileDB-Inc/TileDB-MariaDB/actions/runs/10011046585
[sc-51420]
> use new Array and ArraySchema constructors
