TileDB-Inc/TileDB-MariaDB

README.md, mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile-discovery.cc, mytile/mytile.h, mytile/utils.cc, mytile/utils.h
This adds a new server and session variable `mytile_tiledb_config` which is a csv list of parameters in the form `key1=value1,key2=value2`.
A helper function is also added for creating the tiledb config objects and for splitting a delimited string.
The TileDB config is only set on handler creation or table opening. If you change parameters for a table that is open (such as one recently accessed) then you will need to first `FLUSH TABLES` before the new configuration parameters will take effect.
This was tested by using the `vfs.s3.aws_access_key_id` and `vfs.s3.aws_secret_access_key` to access remote arrays.
=> Support user set tiledb config parameters

.dockerignore, docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server, docker/docker-entrypoint-interactive.sh, docker/docker-entrypoint.sh
This makes the tiledb-mariadb-sever version behave like regular mariadb docker image and makes it compatible with the helm mariadb chart for k8s.
=> Don't preinit the server docker and other misc fixes for server docker image

mysql-test/mytile/r/insert_into_select.result, mysql-test/mytile/t/insert_into_select.test, mytile/ha_mytile.cc
We switch on the bitmap for readset for creating buffers, so we need to make sure its set to all fields. Previously we used `dbug_tmp_use_all_columns` but this only sets it when built in debug mode.
Instead we should use `tmp_user_all_columns`;
It is "read_set" because we use the Field->val_* accessors. So we "read" values from the server into a "tiledb write".
=> Always make sure to set all buffers for writes

README.md, mysql-test/mytile/r/flushing_arrays.result, mysql-test/mytile/t/flushing_arrays.test, mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile-sysvars.h
A new configuration open is given reopen_for_every_query to disable this new behavior. Forcing arrays to be reopened is required to allow TileDB configuration parameters to take effect without flushing tables. Flushing tables is a blocking operation so it might not be desired.
The downside of reopening the arrays by creating new contexts is that any caching or in memory fragments are lost.
=> Support reloading tiledb config for every query

mysql-test/mytile/r/pushdown_ranges.result, mysql-test/mytile/t/pushdown_ranges.test, mytile/ha_mytile.cc, mytile/ha_mytile.h
This fixes cond_push with reopen_for_every_query, where there is more than one cond_push call. We don't want to reopen the array for each pushdown.
Also fixes handling determining if pushdowns are valid or not.
=> Load array schema and store as unique_ptr

mytile/ha_mytile.cc
Dense arrays do not currently support unordered or global or reads for multi-range queries. We should use row-major for now
=> Set read queries to row order for dense arrays

docker/Dockerfile, docker/Dockerfile-server
Don't use verbose mode for tiledb with docker images.
=> Don't build tiledb in verbose mode for non-dev docker

mytile/ha_mytile.cc, mytile/mytile-discovery.cc, mytile/utils.cc
This might have been causing the segfault on OSX with conda env. We don't actually need to create the config or ctx in the constructor so we can call it from member functions if needed.
=> Don't access ha_th() on handler constructor

mytile/ha_mytile.cc
When checking that the range pushdowns are valid we need to not just make sure they are non-empty but also that atleast one of the lower or upper values is set and non null.
=> Validate range values are non-nullptr

mysql-test/mytile/r/join.result, mysql-test/mytile/r/mrr.result, mysql-test/mytile/t/join.test, mysql-test/mytile/t/mrr.test, mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile-range.cc, mytile/mytile-range.h, mytile/mytile-sysvars.cc, mytile/mytile-sysvars.h, mytile/utils.cc, mytile/utils.h
This is a large patchset which adds support for MRR scans, useful for joins. It greatly improves join performance by allowing Batched Key Access (BKA) for joins.
Index scanning was also improved and a new index scan function implemented which will perform a scan on the coordinate buffers to find the key asked for during BKA or full index scan operations.
In addition a new parameter `log_level` is added to allow controlling mytile log messages.
=> Add support for Multi-Range-Reads (MRR) and Index Improvements

docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server, scripts/azure-linux_mac.yml, scripts/ci_install_tiledb_and_run_tests.sh
Update mariadb versions to 10.4.11 for CI and docker. Also update TileDB to 1.7.2 for docker and CI.
=> Update mariadb versions to 10.4.11

mysql-test/mytile/r/empty_records.result, mysql-test/mytile/t/empty_records.test, mytile/ha_mytile.cc, mytile/ha_mytile.h
This changes the empty check to happen inside the scan_rnd_row or index_read_scan functions where MariaDB is expecting the HA_ERR_END_OF_FILE error instead of in init_scan.
=> Empty arrays should return empty dataset not error

mysql-test/mytile/r/mrr_incomplete_queries.result, mysql-test/mytile/t/mrr_incomplete_queries.test, mytile/ha_mytile.cc, mytile/mytile-sysvars.cc, mytile/mytile-sysvars.h
In the future this will be lifted but for now this is how mariadb expects the results.
We also adjust to better handle incomplete queries. With incomplete queries we can work around a missing key in the batch by moving to the next batch. If we've missed the key we will go back and restart the query from the top.
If we complete 1 full scan and don't find a key we will return missing key.
The main purpose of these changes is for correctness of results. Of course in scenarios with unsorted keys were we restart a query from the beginning it is far from ideal performance. However correct results are worth the penalty in these cases.
=> Handle unsorted key joins

mysql-test/mytile/r/open_at.result, mysql-test/mytile/t/open_at.test, mytile/ha_mytile.cc, mytile/mytile-discovery.cc, mytile/mytile.h
A new table option `open_at` is provided to allow users to register a table to be opened for reads at a given time.
This will be rebased after #53  is merged.
=> Add support for open_at via table option

mysql-test/mytile/r/data_types.result, mysql-test/mytile/r/encryption.result, mysql-test/mytile/t/encryption.test, mytile/ha_mytile.cc, mytile/mytile-discovery.cc, mytile/mytile-discovery.h, mytile/mytile.h
Support for creating, reading and writing encrypted arrays is included.
This includes minor modifications to create_array and discover_array in order to allow passing the encryption string to the handler.
Due to a limitation of MariaDB if you pass an encryption key it will be shown in the create table statement.
This will be rebased after #54 and #53 are merged.
=>  Add support for encrypted arrays

mysql-test/mytile/r/filters.result, mysql-test/mytile/r/open_at.result, mysql-test/mytile/r/primary_key.result, mysql-test/mytile/t/filters.test, mytile/ha_mytile.cc, mytile/mytile-discovery.cc, mytile/mytile.cc, mytile/mytile.h
Filters are specified as a CSV list. For filters which take an option, i.e compressions, it is expected in the form `<FILTER_TYPE>=<OPTION_VALUE>` (`GZIP=6`)
Example create table statement:
```
CREATE TABLE t1 (
dim1 bigint dimension=1 lower_bound="0" upper_bound="100" tile_extent="10",
attr1 bigint filters='GZIP=6',
attr2 bigint filters='GZIP=-1',
attr3 bigint filters='GZIP=-1,ZSTD=6',
attr4 bigint filters='BIT_WIDTH_REDUCTION=128',
attr5 bigint filters='POSITIVE_DELTA=128',
attr6 bigint filters='BIT_WIDTH_REDUCTION=138,ZSTD=1,GZIP=1',
attr7 bigint filters='RLE'
) ENGINE=mytile coordinate_filters='LZ4=-1' offset_filters='BZIP2=3';
```
=> Add support for filters in create table

mytile/mytile-discovery.cc, mytile/mytile-discovery.h, mytile/utils.cc, mytile/utils.h
Fix handling discovery of TileDB Cloud Arrays. `tiledb://` arrays are not supported in vfs so we need to handle those by trying to load the array schema.
=> Fix handling discovery of TileDB Cloud Arrays

azure-pipelines.yml, docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server, scripts/azure-linux_mac.yml, scripts/ci_install_tiledb_and_run_tests.sh
This updates CI and the docker files. TileDB <1.7.6 has broken builds due to tbb changing their repo name.
=> Update to TileDB 1.7.6

mytile/mytile-discovery.cc, mytile/mytile.cc
This fixes two problems encountered with an array. First we were not handling Byte/BitShuffle and Double Delta filters properly for filter lists. Second problem was the table discovery was using the wrong string for COLUMN_MAJOR order. It needed to line up with the [table options](https://github.com/TileDB-Inc/TileDB-MariaDB/blob/c7f0949976db92e7e64899af941b7194660698d0/mytile/ha_mytile.cc#L63)
=> Fixes for a failure in table discovery

CMakeLists.txt, docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server, scripts/ci_install_tiledb_and_run_tests.sh
Update to TileDB 2.0.0 for CI, docker and superbuild (which doesn't really work).
=> Update to TileDB 2.0.0

mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile-range.cc, mytile/mytile-range.h
The find_flag from the key has different meanings for if it from a start key or an end key.
This should fix the issue with MariaDB 10.4.12/13 now that the MRR call path is called more often thanks to https://github.com/MariaDB/server/commit/1242eb3d32f2863f847aa96a10e2ab983a1a643b
=> Correct MRR support with start/end keys

CMakeLists.txt, docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server, scripts/azure-linux_mac.yml, scripts/ci_install_tiledb_and_run_tests.sh
This updates the MariaDB version to the latest for 10.4. We also update TileDB to 2.0.2.
=> Update MariaDB for CI and Docker to 10.4.13 

README.md, mysql-test/mytile/r/duplicates.result, mysql-test/mytile/r/flushing_arrays.result, mysql-test/mytile/r/join.result, mysql-test/mytile/r/primary_key.result, mysql-test/mytile/t/duplicates.test, mysql-test/mytile/t/flushing_arrays.test, mysql-test/mytile/t/join.test, mysql-test/mytile/t/primary_key.test, mytile/ha_mytile.cc, mytile/mytile-discovery.cc, mytile/mytile-sysvars.cc, mytile/mytile-sysvars.h
This adds support for duplicate in arrays. A new option for sparse arrays in TileDB 2.0 is to allow duplicates. We now will switch between primary key and index on table discovery and when creating the array we check for if the user specified the primary key (no duplicates) or not (duplicates allowed if sparse).
=> Add support for duplicates in sparse arrays

CMakeLists.txt, docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server, scripts/ci_install_tiledb_and_run_tests.sh
Update to TileDB 2.0.5, specifically this fixes the problem with [GCS causing context to fail to start](https://github.com/TileDB-Inc/TileDB/pull/1667).
We'll cut a new release after this to update the docker and conda packages.
=> Update to TileDB 2.0.5

README.md
`https://hub.docker.com/r` is the public URL for a repo whereas `https://hub.docker.com/repository/docker` requires a login.
=> Fix readme docker links

mytile/mytile-discovery.cc
In array discovery
Omitting the if statement leads to error in mrr test for `bank` array
=> Sets dimension fields to NOT NULL if array allows duplicates

azure-pipelines.yml, docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server, scripts/build-images.yml
Previously the build-arg for docker build was missing to set the mytile version.
We also introduce a new TILEDB_VERSION arg for flexibility
=> Update CI to build proper Docker Image versions

mytile/ha_mytile.cc
If `tiledb://namespace` is not given, and token is set, the array is created in an s3 bucket but not registered with the console.
=> Incorrectly creating array on local disk instead of s3

docker/Dockerfile, docker/Dockerfile-dev, docker/Dockerfile-server
If a user tries to access the AWS S3 arrays but doesn't provide credentials (such as using a public dataset) the SDK tries to lookup
credentials with EC2 metadata IP and this causes a long timeout for curl.
=> Disable AWS SDK from using EC2 metadata in docker

mytile/ha_mytile.cc
This adds HA_FAST_KEY_READ | HA_SLOW_RND_POS to the table options. rnd_pos can be slow in TileDB as these are used for point queries. Also random key reads are as fast as sequential reads for TileDB.
=> Adjust table options for slow rnd_pos and fast key

CMakeLists.txt, azure-pipelines.yml, scripts/azure-linux_mac.yml, scripts/ci_install_tiledb_and_run_tests.sh
When building TileDB from source we now properly copy over the non-symlinked library.
=> Improve superbuild library copying

mytile/mytile.cc
Array discovery is using NaN for float / double values as retrieved from get_fill_value. This change detects that and uses 0.0 instead.
=> use 0 for default float / double nan fill values

mytile/ha_mytile.cc, mytile/mytile-errors.h, mytile/mytile.h
This fixes the crash (signal 6 abort) when creating an array dimension without a tile_extent. All error codes were moved into a common enum.
=> catch exception on dimension create, move err codes to header

mysql-test/mytile/r/create_allow_subset_existing_array.result, mysql-test/mytile/t/create_allow_subset_existing_array.test, mytile/ha_mytile.cc, mytile/mytile-sysvars.cc, mytile/mytile-sysvars.h
If a TileDB array has more than the 4096 max columns that MariaDB supports we want to allow the user to issues a create table statement to register a subset of the dimensions/attributes. This behavior is controlled by the new `mytile_create_allow_subset_existing_array` session parameter. The default behavior, error if issuing a create table with columns on an existing, is left intact as for most users they will not want subsetting but instead likely would be trying to create a
new array.
Example SQL usage on an array which has 5k attributes:
```
MariaDB [test]> create table test_1 engine=MyTile uri='/tmp/attributes_5k';
ERROR 1939 (HY000): Engine MyTile failed to discover table `test`.`test_1` with 'create table `test_1` (
`d0` INTEGER dimension=1 lower_bound='0' upper_bound='10000000' …
```
=> Add support for subsetting an array on discovery

scripts/azure-linux_mac.yml
Reverts TileDB-Inc/TileDB-MariaDB#119
Workaround is no longer needed.
=> Revert "Workaround homebrew openssl error for CI"

mytile/mytile-discovery.cc, mytile/mytile.cc, mytile/mytile.h
TileDB's default fill_in value for strings is not compatible with mariadb ansi expectations (i.e. for char TileDB uses \200). The quick
solution is to only tell MariaDB about default values if they are custom or if they are default but not string datatypes.
=> Only set default values if custom or not string

docker/docker-entrypoint-interactive.sh, docker/docker-entrypoint.sh
Launching the `tiledb/tiledb-mariadb` and `tiledb/tiledb-mariadb-server` docker images currently result in an infinite loop waiting for MariaDB to initialize due to the following error: `The user specified as a definer ('mariadb.sys'@'localhost') does not exist`.
This change adds the `mariadb.sys` user to the exclusion list. More information on the MariaDB changes that caused this problem can be found in the comments of [this ticket](https://jira.mariadb.org/browse/MDEV-22542).
=> Added mariadb.sys user to the list of system users to fix Docker entrypoint

CMakeLists.txt, mysql-test/mytile/my.cnf.in
adds a confugure_file step to CMakeLists which enables/disables mytile plugin loading in my.cnf depending on the value of WITH_EMBEDDED_SERVER.
=> conditionally include plugin load add for mytile based on embedded build

mysql-test/mytile/r/datetime_pushdown.result, mysql-test/mytile/t/datetime_pushdown.test, mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile-range.cc, mytile/mytile-range.h
If the condition being pushed is a datetime we need to handle and check for Item_cache_datetime types to avoid a segfault when we incorrectly casted the Items to Item_basic_constant.
=> Handle datetime pushdown with Item_cache_datetime

mysql-test/mytile/r/string_dim.result, mysql-test/mytile/t/string_dim.test, mytile/ha_mytile.cc, mytile/mytile-range.cc, mytile/mytile-range.h
This fixes two issues, the first being that we incorrectly were copying the key for pushdown onto the TileDB range. We were accidentally only considering the first character instead of all characters.
Second we were not handling partial key matches. For strings a partial key comparison might include zero length keys, which should be considered for any match. This adjusts to capture the comparison of zero length string.
=> Fix handling of string key comparison and ranges

mysql-test/mytile/r/string_dim.result, mysql-test/mytile/t/string_dim.test, mytile/ha_mytile.cc
In handling the option for computing the number of records in an array, we were missing handling string based dimensions. This adds a check to handle this case.
=> Handle var length dims in compute_table_records

mytile/ha_mytile.cc, mytile/ha_mytile.h
For variable length dimensions we were resetting the `ref_length` and reallocating `ref` when the handler called for `position()` based on the string size of the current coordinates. This doesn't work for MRR cases though because the address of `ref` is taken before `position()` is called.
The quick fix is we'll always set the `ref_length` to the maximum allowed size of a row. This means we'll allocate an extra 65KB, but in the grand scheme this is insignificant for most usages and we only generally store a small amount of positions.
=> ref for position can't be reset with MRR

mytile/mytile.cc
Previously we were using system timezone to convert to UTC, this meant queries were off compared to what the user expected.
No unit test was added because in the test env (azure pipelines) we don't have timezones loaded so everything is always UTC. I didn't think it was worth the effort right now to set that up.
=> Converting MariaDB datatime should always use UTC

mysql-test/mytile/r/mrr_datetime_dimensions.result, mysql-test/mytile/t/mrr_datetime_dimensions.test, mytile/ha_mytile.cc, mytile/mytile-range.cc, mytile/mytile-range.h, mytile/mytile.cc
Handle datetime in MRR key merging, this fixes an issue with a customer query where due to the size the condition was being applied as MRR.
=> Handle datetime in MRR key merging

docker/docker-entrypoint-interactive.sh
My attempt in #134 to fix the infinite waiting when launching the interactive Docker image, unfortunately, didn't resolve the problem. The current `docker-entrypoint-interactive.sh` entry point used in some of the Dockerfiles still suffers from infinite waiting because of: `The user specified as a definer ('mariadb.sys'@'localhost') does not exist`
The following change now addresses the issue, and upon running the container a user is dropped inside a MariaDB shell. The solution was to query the `mysql.global_priv` table instead of `mysql.user` per [the following clafirication](https://jira.mariadb.org/browse/MDEV-22909?focusedCommentId=157925&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-157925) that MariaDB in 10.4 uses `mysql.global_priv` and older …
=> Updated docker-entrypoint-interacitve startup query ot use mysql.global_priv table

mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile-sysvars.cc, mytile/mytile.cc, mytile/mytile.h
Instead of allocating based on the user set buffer size, we now let the user set a memory budget for the total buffer size of a query. This allows better control of the memory usage, as the user might not always know the number of fields to be selected. This allow update to allocate buffer based on the size in bytes of the datatype in order to more efficiently allocate memory.
=> read/write_buffer_size  is now total budget

mysql-test/mytile/r/datetime_pushdown.result, mysql-test/mytile/r/estimated_table_records.result, mysql-test/mytile/r/join.result, mysql-test/mytile/r/mrr.result, mysql-test/mytile/r/mrr_heterogeneus_dimensions.result, mysql-test/mytile/r/mrr_incomplete_queries.result, mysql-test/mytile/r/mrr_string_dim.result, mysql-test/mytile/r/primary_key.result, mytile/ha_mytile.h, scripts/ci_install_tiledb_and_run_tests.sh
Computing the actual row count is optional as it can be a costly operation. Instead we have a hard coded value which MariaDB uses to make determination about the query plan. The previous value of 2, was too low and causing poor query performance as MariaDB often attempted a linear scan instead of using the "indexes" to pushdown the ranges.
The previous value of 2 was left over from initial development and this was suppose to have been increased along with the `records_in_range` value.
=> Increase default row count to 100000

CMakeLists.txt, docker/Dockerfile, docker/Dockerfile-R, docker/Dockerfile-dev, docker/Dockerfile-min, docker/Dockerfile-server, mytile/ha_mytile.cc, mytile/mytile-metadata.cc, mytile/mytile-metadata.h, mytile/mytile-range.cc, mytile/mytile.cc, mytile/mytile.h, scripts/ci_install_tiledb_and_run_tests.sh
This PR updates to TileDB 2.3 and adds support for the new TileDB Time datatypes to match the MariaDB TIME data type. Previously we were putting TIME types in `TILEDB_DATETIME` fields. Now we store them as proper `TILEDB_TIME_MS`.
No new unit tests are added because we already had unit tests for time datatypes, so they cover the new functionality.
=> Add support for TileDB Time Datatypes and TileDB 2.3

CMakeLists.txt, docker/Dockerfile, docker/Dockerfile-R, docker/Dockerfile-dev, docker/Dockerfile-min, docker/Dockerfile-server, mysql-test/mytile/r/data_types.result, mysql-test/mytile/r/query_conditions.result, mysql-test/mytile/t/data_types.test, mysql-test/mytile/t/query_conditions.test, mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile-range.cc, mytile/mytile-range.h, scripts/ci_install_tiledb_and_run_tests.sh
This pushes down filtering on the attribute field. This is currently limited to AND clauses with basic predicates of `>`/`>=`/`=`/`<=`/`<`/`!=` along with `IS NULL` and `IS NOT NULL`.
At this time I opted to re-use the existing range building functionality we have. This minimized the changes needed to start with.
=> Add QueryCondition pushdown support

docker/Dockerfile-min
The minimized dockerfile copies the build and libraries into a new image using the multi-stage build to minimize the size. The changes to use prebuilt-tiledb artifacts overlooked that the location of TileDB needed to be taken into account when copying.
=> Dockerfile-min needs to copy prebuilt TileDB lib

mytile/ha_mytile.cc, mytile/mytile.h
The ENUM values for table options need to be `uint` not `ulonglong`. Also the order of the options struct differed between the data struct and the option definition.
=> Fix table option for cell/tile layout

mytile/ha_mytile.cc, mytile/mytile-range.cc, mytile/mytile-range.h
This fixes four problems:
1) `set_range_from_item_consts` was missing switch case for strings, so pushdown via `cond_push` was not support previously (only through index pushdown)
2) We were not correctly checking and bailing early in `cond_push` when the condition was not a constant but was other fields
3) We incorrectly were supporting IN clauses for QueryCondition with pushdown of attribute fields. TileDB core library currently doesn't support `OR` or `IN` clauses for attribute pushdown
4) We were not exiting early in `cond_push` when we had an attribute that we couldn't use pushdown on, this causes error in trying to set ranges for dimensions instead in the fallback
=> Fix string pushdown for query condition and ranges

mytile/ha_mytile.cc, mytile/mytile-range.cc, mytile/mytile-range.h, scripts/azure-linux_mac.yml
This PR has a few fixes, first we set the dimension order to be the same as the index orders. Next we properly handle MRR keys to only increment the last_key part. That is for MariaDB when using non-inclusive ranges, only the last part of the key is expected to be incremented.
Lastly we handle the key_length not being the same as the TileDB datatype.
=> Fix index handling in 10.5

docker/Dockerfile, docker/Dockerfile-R, docker/Dockerfile-dev, docker/Dockerfile-min, docker/Dockerfile-server
Update server docker image to use prebuilt TileDB. This fixes a timeout / reduces CI runtime for building the docker image. We use prebuilt library for all over docker images.
=> Update server docker image to use prebuilt TileDB

mytile/ha_mytile.cc
This fixes a problem where errors in the init sequence of MRR were not causing the user to get the error returned to them. This fixes also a cause where we would segfault by continuing the query when it was not properly init'ed.
=> Check return code of `build_mrr_ranges`

mytile/ha_mytile.cc, mytile/mytile-range.cc, mytile/mytile-range.h
This removes an unnecessary casting that was causing a segfault in the range pushdown for datetimes. There was an incorrect dynamic cast to change the Item pointer type. This is not needed and the `Item*` can be left as is.
=> Remove unnecessary casting for Datetime pushdown

mysql-test/mytile/r/datetime_pushdown.result, mysql-test/mytile/r/mrr.result, mysql-test/mytile/r/mrr_datetime_dimensions.result, mysql-test/mytile/r/mrr_heterogeneus_dimensions.result, mysql-test/mytile/r/mrr_incomplete_queries.result, mysql-test/mytile/r/mrr_string_dim.result, mysql-test/mytile/t/mrr.test, mysql-test/mytile/t/mrr_datetime_dimensions.test, mysql-test/mytile/t/mrr_heterogeneus_dimensions.test, mysql-test/mytile/t/mrr_incomplete_queries.test, mysql-test/mytile/t/mrr_string_dim.test, mytile/ha_mytile.cc, mytile/mytile-sysvars.cc, mytile/mytile-sysvars.h
RR is most useful for joins and bulk key access (BKA). MariaDB however also attempts to use MRR if implemented for quick selects. This introduces a new sysvar `mytile_mrr_support` which toggles whether MRR is enabled or if its treated as disable and unavailable.
[sc-18106]
=> Disable MRR by default

.github/workflows/nightly.yaml
Notes:
* Opens an Issue using the GitHub CLI command `gh issue create`. See [docs](https://cli.github.com/manual/gh_issue_create) for available flags
* Inspired by the [functionality](https://github.com/TileDB-Inc/TileDB-Py/blob/4f9ed6aedd5c4e499beb533378305ced6d29520f/.github/workflows/daily-test-build.yml#L78) in the TileDB-Py nightly build
* Issue includes a link to the failed run
Questions:
* Should any other users be automatically assigned to the Issue?
* Can only use existing Issue labels. Instead of generic "bug", should we create a specific one, eg "nightly"? This would make it easier to filter these automated Issues from other bug reports
=> Open Issue for failed nightly build

mytile/ha_mytile.cc, mytile/mytile-statusvars.cc, mytile/mytile-statusvars.h
This introduces a new status variable for the TileDB version. 
```
MariaDB [(none)]> show status like '%mytile%';
+-----------------------+--------+
| Variable_name         | Value  |
+-----------------------+--------+
| Mytile_tiledb_version | 2.12.3 |
+-----------------------+--------+
1 row in set (0.001 sec)
```
=> Add tiledb version to show status

scripts/azure-linux_mac.yml, scripts/nightly/setup-macos.sh
libjudy is required by MariaDB's optional OQGraph plugin, which we do not need for nightly testing. The homebrew package is unmaintained and regularly fails to install.
We'll still have coverage on linux.
Fixes https://github.com/TileDB-Inc/TileDB-MariaDB/issues/214
=> Remove macOS installation of libjudy

.github/workflows/nightly.yaml, scripts/nightly/open-issue.sh
I made the following improvements to the issue-opening functionality:
* An Issue will only be opened if the build fails in a scheduled build on the main repo. In other words, it won't try to open an Issue on a fork, and it also won't attempt to open an Issue when building from a push to a branch or pull request. The advantage is that we can still test updates to the nightly build (eg enable a feature) without always opening an Issue
* When a scheduled nightly build fails, it will only create a new Issue if one doesn't currently exist. If there is already an open Issue with the label "nightly-failure", it simply comments with a link to the latest failed build log
* I removed my username from `--assignee`. Since I don't have write access to this repo, I can't be assigned to Issues
Note that …
=> Improve auto issue opening when a nightly build fails

scripts/nightly/build-libtiledb.sh
This PR fixes issue #242. The problem was that libtiledb could not be found by ```find_package(TileDB QUIET)```. The issue was resolved by adding the ```--prefix``` cmake flag.
=> fixing issue 242

mytile/ha_mytile.cc, mytile/ha_mytile.h
Read shortcut story for more details about the bug. 
I reproduced it locally by downloading the TileDB array stored in s3 https://cloud.tiledb.com/arrays/details/TileDB-Inc/504e9cc6-e8c4-4609-a5a4-1d243a9a7d1b/overview. 
The bug was happening when we were reading an array with dims of mixed type. (String and Numeric). More specifically,  when filtering on the String dim only, MyTile was failing to verify that the other dim matched the MariaDB key. This checking algorithm is part of MyTile  and was modified to avoid the bug. 
I am not including any new tests in this PR since the only array (as far as I know) that had this bug is 600MB. In smaller arrays the bug was not present. (Multiple read batches are required). 
A full reproduction can be found here: …
=> fix string dim slicing bug

mysql-test/mytile/r/schema_evolution.result, mysql-test/mytile/t/schema_evolution.test, mytile/ha_mytile.cc, mytile/ha_mytile.h
This PR adds support for the ```ALTER TABLE ADD/DROP``` operations in MyTile by using the ```SchemaEvolution``` API. All other requests will return an error message.
Users can now drop one or more columns by name:
```ALTER TABLE `table` DROP `a3`, DROP `a4`;```
Or add new attributes and configure them the same way they do when they use ```CREATE_TABLE```
```ALTER TABLE `table` ADD COLUMN (`a10` int filters='GZIP=6');```
[sc-30285]
=> add support for ALTER TABLE ADD/DROP

mysql-test/mytile/r/spatial_index.result, mysql-test/mytile/t/spatial_index.test, mytile/ha_mytile.cc, mytile/ha_mytile.h, mytile/mytile.cc
Changes:
- Adds a `cond_push_func_spatial` function to handle  `ST_Intersection` and similar spatial functions, which adds a range pushdown to `_X` and `_Y` dimensions. See [paper doc](https://www.dropbox.com/scl/fi/pd36ldxrh7lz1p08km6so/MariaDB-Spatial-SQL.paper?dl=0&rlkey=nvkvcvaqqmu2zgy0drz2x6czs) for more details.
- Map the MySQL Blob types to TILEDB_BLOB. This enables creation of blob attributes with CREATE SQL statements (previously resulting in char).
=> Add a pushdown for geometry types

.github/workflows/nightly.yaml, scripts/nightly/setup-ubuntu.sh
This compilation error was caused because we were using gcc 9. I have updated the nightly script to use ```ubuntu-22.04``` which uses gcc 11. I think it's better than manually updating the gcc in the older image.
=> updating ubuntu image to ```ubuntu-latest``` for nightly builds

mytile/mytile-statusvars.cc
The exported status variables array should end with a null-like struct, the absence of that final null-like struct causes mysqld to crash on macos.
@Shelnutt2 I've mentioned this to you when I last debugged something in mytile, but back then I just worked around and moved on.
=> Fix mysqld crash on Macos

scripts/nightly/build-tiledb-mariadb.sh
The CMake variable `TILEDB_FORCE_ALL_DEPS` should be set to `ON` or `OFF`. I accidentally had the backup value set to `NO`
This change will have no immediate effect since I set the env var `TILEDB_FORCE_ALL_DEPS` in the nightly workflow file:
https://github.com/TileDB-Inc/TileDB-MariaDB/blob/cacc61994e2b9b9a37387eea2bfc14220c375cc4/.github/workflows/nightly.yaml#L23
=> Set backup value of TILEDB_FORCE_ALL_DEPS to OFF in nightly build

.github/workflows/docker.yaml, .github/workflows/stable.yaml
This PR should fix the issue with `docker-login` action not being able to see secrets.
Tested with custom dockerhub account: https://github.com/dudoslav/TileDB-MariaDB/actions/runs/7244763800/job/19733614867
Note that this pipeline fails because of Dockerfile using hard coded links for THIS repo.
=> Fix secret passing between workflows

.github/workflows/stable.yaml
This PR adds superbuild variant into CI/CD matrix for Linux platform only, since the Mac OS superbuild does not work yet.
=> Add superbuild configuration into CI/CD stable matrix

.github/workflows/stable.yaml
The new GitHub Action workflow `docker` failed when run on my fork. I updated the workflow `stable` to only call `docker` when the repository owner is `TileDB-Inc`
Other notes:
* The `${{}}` aren't required in `if:`, eg [these examples](https://github.com/search?q=language%3Ayaml%20path%3A.github%2Fworkflows%20startsWith&type=code)
* The `if:` statement is now quite long. I can reformat it if desired, eg
```yaml
if: |
github.repository_owner == 'TileDB-Inc'
&& 
(
startsWith(github.ref, 'refs/tags/')
||
github.ref_name == github.event.repository.default_branch
)
```
=> Do not run Docker builds on forks

scripts/ci/setup-macos.sh
Removing cmake from the ```brew install``` list prevents it from being upgraded to 3.29.1 as the runners currently have 3.29.0 installed. We will have a fix for core by the time the runners upgrade to cmake 3.29.1 so there is no need to file a follow-up story here. 
Nightly:
https://github.com/TileDB-Inc/TileDB-MariaDB/actions/runs/8603000565/job/23573846830
=> pin cmake to 3.29.0

.github/workflows/docker.yaml, .github/workflows/nightly.yaml, .github/workflows/stable.yaml
https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/
=> Migrate GitHub Actions to Node 20

docker/Dockerfile-R, docker/Dockerfile-server
Leftover typo from previous #346 that caused the master CI failures
=> fix wrong paths in ```DockerFile-R``` and ```Dockerfile-server```

.github/workflows/docker.yaml, docker/Dockerfile, docker/Dockerfile-R, docker/Dockerfile-dev, docker/Dockerfile-min, docker/Dockerfile-server
This PR will fix the main branch failures. The introduction of #346 is causing failures in the Dockerfile-R. The failures have to do with the fact the this is the only file that builds mariadb in "embedded" mode. This dockefile is not used anymore so it is removed by this PR. In addition to that, the download links for mariadb have been updated.
A successful run can be seen here https://github.com/DimitrisStaratzis/TileDB-MariaDB/actions/runs/9758760985/job/26934249792. The failures are because of the docker hub credentials. the images are built fine. 
[sc-50453]
=> fix Dockerfile download links

mytile/mytile.cc
Found this while debugging some other issues. 
Querying https://cloud.tiledb.com/arrays/details/TileDB-Inc/23fe2f0d-74cc-4ee8-b191-ffaefe4aabc6 was failing. It is now fixed
=> correct condition for fixed sized attributes

mysql-test/mytile/r/pushdown_two_predicates.result, mysql-test/mytile/t/pushdown_two_predicates.test, mytile/ha_mytile.cc
Fixes a bug that when in a combined condition we were combining a dim and an attribute and the dim was first. 
E.g. ```select * from array where d1 > 3 and a > 4```
Without the fix the query could work by reversing the order:
E.g. ```select * from array where a > 4 and d1 > 3```
=> Algorithm bug fix for AND/OR

mytile/ha_mytile.cc, mytile/ha_mytile.h
The group_by handler for aggregates opens the array we are querying as aggr_array to validate whether we can push down the aggregation to TileDB. If the pushdown isn't possible, we weren't closing the array, which caused the deletion issue
On top of that, Theo changed ```aggr_array``` to a smart pointer which is a nice bonus.
Thanks to @teo-tsirpanis for figuring out what the problem was!
To validate this fix I used an already existing array ```theo```.
And created a test that runs a simple query on it:
``` sql
--replace_result $MTR_SUITE_DIR MTR_SUITE_DIR
--eval CREATE TABLE theo ENGINE=mytile uri='$MTR_SUITE_DIR/test_data/theo';
select * from theo; 
```
I inserted the following line in the close() method of the mytile handler:
```cpp
tiledb::Array::delete_array(this->ctx, this->uri); …
```
=> Fix leak of `mytile_group_by_handler::aggr_array`.

README.md
https://linear.app/tiledb/issue/TAB-55/mark-mytile-repos-as-deprecated
=> Deprecation info
